# contract_terms = [
#     "Warranty provisions", "Governing Law of the Contract", "Tax provisions", 
#             "Performance Security", "Termination by Contractor", 
#             "Pre-requisite for Commencement of Work", "Limitation of Liability", 
#             "Liquidated Damages", "Contract Price Adjustment / Price Escalation", 
#             "Extension of Time provisions", "Service Level Agreement (SLA)", 
#             "Insurance Requirements", "Confidentiality Obligations", 
#             "Requirement of Permanent Assets / Establishment in the Country", 
#             "Retention Money provisions", "Payment Terms", "Consequential Losses", 
#             "Indemnities", "Change In Law", "Exceptional Events / Force Majeure", 
#             "Suspension Provisions", "Termination by Employer", 
#             "Variation / Change Order Provisions", "Provisional Acceptance / PAC", 
#             "FINAL Acceptance / FAC", "HSE/ Health Safety Environment", 
#             "Integrity Provisions","Order of Precedence","Dispute Resolution","Permits / Imports / Customs","Acceleration provisions",
#             "Incoterms"
# ]


# analytics_ques_list = [
#   "What is the warranty period and warranty conditions mentioned in the document? Please include the duration of the warranty (in months/years), any conditions or limitations, and any specific provisions related to the warranty coverage for the products or services. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Which law governs the contract? Highlight the governing country and law details. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Summarize tax provisions in the document, including any relevant details on tax obligations, exemptions, and procedures related to taxation for the parties involved. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Summarize the performance security details along with time period and procedures. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Summarize the provisions related to termination by contractor as specified in the document, including any conditions, reasons, and procedures outlined for the contractor's right to terminate the contract. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What is the pre-requisite for the commencement of work as mentioned in the document? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Summarize the limitation on liability mentioned in the document in 2 or 3 sentences. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Summarize liability for liquidated damages provisions, including delay liquidated damages and performance liquidated damages, applicable cap, and whether they are exclusive remedies. Capture the key points and highlight the same. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Summarize price adjustment or escalation modality outlined in the document, including any terms, conditions, and mechanisms related to adjustments or escalations in pricing over time. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Give the details about the extension of time as mentioned in the document and summarize the procedure to claim an extension of time. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Are there any service level agreements (SLA) in the document? Summarize them in plain text without any special characters, formatting, or HTML tags.",
#     "Give a summary of insurance terms in bullet points along with procedures to claim them. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Summarize confidentiality obligations outlined in the document, including any relevant terms, conditions, and obligations pertaining to the protection of sensitive information. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the country-specific requirements for permanent establishment? What are the requirements for permanent assets in the country? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the policies and conditions mentioned for payment/money retentions? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Extract and summarize the payment terms specified in the document, including details on payment methods, deadlines, and any conditions or requirements related to the payment transactions between the parties. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the provisions regarding consequential losses? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the indemnity clauses? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "How is a change in law addressed? Analyze in-depth and give the key features in bold. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the provisions for exceptional events or force majeure? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the suspension provisions? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Under what conditions can the employer terminate the contract? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the provisions for variation or change orders? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the conditions for provisional acceptance (PAC)? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the conditions for final acceptance (FAC)? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the health, safety, and environment (HSE) requirements? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the integrity provisions? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What is the order of precedence of documents specified in the contract? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the dispute resolution procedures outlined in the contract? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the requirements for permits, imports, and customs as per the contract? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "How does the contract address acceleration of timelines or deliverables? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Which Incoterms are applicable to the contract, and how are they defined? Return the response in plain text without any special characters, formatting, or HTML tags."
# ]


download_ques_list = ['Is total limitation of liability "100%" of contract value ?',
                    'Is total limitation of liability with carve outs / exceptions?', 
                    'Is the Liquidated Damages (LDs) for Performance in the contract terms less than "5%" of contract value against agreed PG parameters ?',
                    'Is the Liquidated Damages (LDs) for Delay in the contract terms less than "0.5%" per week of delay from contract delivery date or upto "5%" of contract value ?', 
                    'Did the contract contain an express exclusion of liability for consequential losses and if that is to be borne or accepted by the one who accepts the contract ?', 
                    'Is Force Majeure clause mentioned in the contract and acceptable?',
                    'Is the Length of warranty 12 months from commissiong/handover or 18 months from delivery whichever ends earlier ?', 
                    'Has the Customer the right to suspend for ABBs breach? Is there a clause entitling the customer to terminate for convenience?',
                    'Has ABB the right to suspend for customers breach?',
                    'Is there a clause entitling the customer to terminate for convenience?',
                    'Is there Warranty start latest clause in the document? Is Repair/replacement customers exclusive remedy?',
                    'Does the replaced/repaired part carry an evergreen warranty (unlimited in time)?',
                    'Is ABB entitled to cost compensation for delays caused by customer?',
                    'Is ABB entitled to time extension for delays caused by customer?',
                    'Any Advance payment and retention?',
                    'What are the payment terms and Price Format?'
                    ]


# # Updated contract terms
# contract_terms = [
#     "Warranty provisions", "Governing Law of the Contract", "Tax provisions", 
#     "Performance Security", "Termination by Contractor", 
#     "Pre-requisite for Commencement of Work", "Limitation of Liability", 
#     "Liquidated Damages", "Contract Price Adjustment / Price Escalation", 
#     "Extension of Time provisions", "Service Level Agreement (SLA)", 
#     "Insurance Requirements", "Confidentiality Obligations", 
#     "Requirement of Permanent Assets / Establishment in the Country", 
#     "Retention Money provisions", "Payment Terms", "Consequential Losses", 
#     "Indemnities", "Change In Law", "Exceptional Events / Force Majeure", 
#     "Suspension Provisions", "Termination by Employer", 
#     "Variation / Change Order Provisions", "Provisional Acceptance / PAC", 
#     "FINAL Acceptance / FAC", "HSE/ Health Safety Environment", 
#     "Integrity Provisions", "Order of Precedence", "Dispute Resolution", 
#     "Permits / Imports / Customs", "Acceleration provisions", "Incoterms",
#     "Contract Extension", "Intellectual Property Rights", "Subcontracting"
# ]

# # Updated analytics questions list based on the prompts
# analytics_ques_list = [
#     "What is the warranty period and warranty conditions mentioned in the document? Please include the duration of the warranty (in months/years), any conditions or limitations, and any specific provisions related to the warranty coverage for the products or services. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Which law governs the contract? Highlight the governing country and law details. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Summarize tax provisions in the document, including any relevant details on tax obligations, exemptions, and procedures related to taxation for the parties involved. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Summarize the performance security details along with time period and procedures. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Summarize the provisions related to termination by contractor as specified in the document, including any conditions, reasons, and procedures outlined for the contractor's right to terminate the contract. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What is the pre-requisite for the commencement of work as mentioned in the document? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Summarize the limitation on liability mentioned in the document in 2 or 3 sentences. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Summarize liability for liquidated damages provisions, including delay liquidated damages and performance liquidated damages, applicable cap, and whether they are exclusive remedies. Capture the key points and highlight the same. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Summarize price adjustment or escalation modality outlined in the document, including any terms, conditions, and mechanisms related to adjustments or escalations in pricing over time. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Give the details about the extension of time as mentioned in the document and summarize the procedure to claim an extension of time. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Are there any service level agreements (SLA) in the document? Summarize them in plain text without any special characters, formatting, or HTML tags.",
#     "Give a summary of insurance terms in bullet points along with procedures to claim them. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Summarize confidentiality obligations outlined in the document, including any relevant terms, conditions, and obligations pertaining to the protection of sensitive information. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the country-specific requirements for permanent establishment? What are the requirements for permanent assets in the country? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the policies and conditions mentioned for payment/money retentions? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Extract and summarize the payment terms specified in the document, including details on payment methods, deadlines, and any conditions or requirements related to the payment transactions between the parties. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the provisions regarding consequential losses? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the indemnity clauses? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "How is a change in law addressed? Analyze in-depth and give the key features in bold. Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the provisions for exceptional events or force majeure? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the suspension provisions? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Under what conditions can the employer terminate the contract? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the provisions for variation or change orders? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the conditions for provisional acceptance (PAC)? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the conditions for final acceptance (FAC)? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the health, safety, and environment (HSE) requirements? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the integrity provisions? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What is the order of precedence of documents specified in the contract? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the dispute resolution procedures outlined in the contract? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the requirements for permits, imports, and customs as per the contract? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "How does the contract address acceleration of timelines or deliverables? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "Which Incoterms are applicable to the contract, and how are they defined? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the provisions for contract extension? Summarize in plain text without any special characters, formatting, or HTML tags.",
#     "What are the intellectual property rights specified in the document? Return the response in plain text without any special characters, formatting, or HTML tags.",
#     "What are the terms for subcontracting, including any restrictions or requirements for approval? Return the response in plain text without any special characters, formatting, or HTML tags."
# ]

contract_terms=[
    'Warranty provisions',
    'Governing Law of the Contract',
    'Tax provisions',
    'Security for Performance ',
    'Termination by Contractor',
    'Pre-requisite for Commencement of Work',
    'Limitation of Liability',
    'Liquidated Damages',
    'Contract Price Adjustment / Price Escalation',
    'Extension of Time provisions',
    'Service Level Agreement (SLA)',
    'Insurance Requirements',
    'Confidentiality Obligations',
    'Requirement of Permanent Assets / Establishment in the Country',
    'Retention Money Provisions related to payment procedures ',
    'Payment Terms',
    'Consequential Losses ',
    'Indemnities',
    'Change In Law ',
    'Exceptional Events / Force Majeure',
    'Suspension Provisions',
    'Termination by Employer',
    'Variation / Change Order Provisions',
    'Provisional Acceptance / PAC',
    'FINAL Acceptance / FAC',
    'HSE/ Health Safety Environment ',
    'Integrity provisions',
    'Order of Precedence',
    'Dispute Resolution',
    'Permits / Imports / Customs',
    'Acceleration provisions',
    'Incoterms',
    'Withholding right for ABB',
    'Notices',
    'Milestones'
]

# analytics_ques_list = [
#     "What are the warranty conditions mentioned in the document. Also include duration of the warranty (in months/years), any conditions or limitations, notices, and any specific provisions related to the warranty coverage for the products or services.Do not include introductory statements highlight the key points.",
#     "Give the details of the governing law as mentioned in the document.Do not include introductory statements highlight the key points.",
#     "Summarize tax provisions in the document, including any relevant details on tax obligations, exemptions, and procedures related to taxation for the parties involved.Do not include introductory statements highlight the key points.",
#     "Summarize the details of the requirements along with peri-od/deadlines and procedures for any security for performance in the form of a letter of credit, parent company guarantee, bond and or guarantee that ABB must provide under the contract.Do not include introductory statements highlight the key points.",
#     "Does the contract contain provision(s) for termination by Contrac-tor? If yes, summarize the provisions related to termination by con-tractor (for employer’s default, for convenience, or other) as speci-fied in the document, including any conditions, reasons, and proce-dures outlined for the contractor's right to terminate the contract.Do not include introductory statements highlight the key points.",
#     "Are there any pre-requisite(s) for the commencement of work men-tioned in the document, including any requirements of a Notice to Proceed or the issuance of a Purchase Order.  If yes, provide details, including timeframes/deadlines, for fulfilling said pre-requisite(s). .Do not include introductory statements highlight the key points.",
#     "Summarize the limitation on liability mentioned in the document in 2 or 3 sentence. Does the document have a limitation of liability provision? Specify the limit and any exclusions, if any.Do not include introductory statements highlight the key points.",
#     "Summarize liability for liquidated damages provisions, including delay liquidated damages and performance liquidated damages, applicable cap and whether they are exclusive remedies.Do not include introductory statements highlight the key points.",
#     "Summarize price adjustment or escalation modality outlined in the document, including any terms, conditions, and mechanisms related to adjustments or escalations in pricing over time.Do not include introductory statements highlight the key points.",
#     "Give the details about the extension of time as mentioned in the document and summarise procedure to claim extension of time.Do not include introductory statements highlight the key points.",
#     "Are there any service level agreement (SLA) in the document?.Do not include introductory statements highlight the key points.",
#     "Give a summary of insurance terms in bullet points along with procedures to claim it.Do not include introductory statements highlight the key points.",
#     "Summarize confidentiality obligations outlined in the  document, including any relevant terms, conditions, and obligations pertaining to the protection of sensitive information.Do not include introductory statements highlight the key points.",
#     "What are the country specific requirements for permanent establishment? What are the requirements for permanent assets in the country?.Do not include introductory statements highlight the key points.",
#     "Are there any conditions mentioned in the document allowing the employer to withhold, as retention, a proportion of an amount of money due to the contractor from a payment? Additionally, summa-rise the conditions and procedures for the release of the retention including the point at which the retention money, or part thereof, is required to be paid back to the contractor?.Do not include introductory statements highlight the key points.",
#     "Extract and summarize the payment terms specified in the document, including details on payment methods, deadlines, and any conditions or requirements related to the payment transactions between the parties.Precisely provide the exact prompt response highlighting the key points.Do not include introductory statements highlight the key points.",
#     "Are consequential losses excluded or limited. Does the document have an exclusion for consequential losses provision? Specify any exclusions, if any.Do not include introductory statements highlight the key points.",
#     "Are there any indemnity provisions in the contract? What is the extent of indemnification and who is to be indemnified? Are indemnities included/capped under the limitaton of liability provision?.Do not include introductory statements highlight the key points.",
#     "Does the contract have a change in law provision? Please specify any exclusions, if any.Do not include introductory statements highlight the key points.",
#     "Does the contract include the right to terminate for force majeure/exceptional events? If yes, who has the right to terminate and under what circumstances. What is the notification period for such events and is there any specific format stipulated by the contract in which such event is to be notified?  Identify provisions that differs from ABB requirements/standards (e.g. Material shortage, ripple effect, COVID-19).Do not include introductory statements highlight the key points.",
#     "Summarise in bullet point format the causes for suspension by contractor or employer? What is the notification period for such suspension events and is there any specific format stipulated by the contract in which such event is to be notified? Can the contractor claim costs due to a suspension? if yes, under what circumstances.  Does the document include right to terminate for suspension? If yes, who has the right to terminate and under what circumstances.Do not include introductory statements highlight the key points.",
#     "Does the contract contain provisions for termination by employ-er?  When does it entitle the employer to terminate? Summarise any provisions entitling the employer to terminate for convenience, in-cluding list contractor’s recoverable costs and expenses and other relevant information? What are the termination provisions due to breach of contract by contractor? Is there a period/deadline by which the contractor is required to respond or take action to avoid termination by the employer due to contractor’s breach? .Do not include introductory statements highlight the key points.",
#     "Does the contract allow the employer to direct/instruct  the contractor to perform a variation/change before mutual agreement? What are the conditions in which a variation or change order is claimable? What are the notification requirements? What is the timebar requirement? Is there a procedure to invoice changes/ variations? Does the contractor have a duty to perform and upon which conditions? Can the contractor reject a variation/change if it does not align with geographical and scope connectivity?.Do not include introductory statements highlight the key points.",
#     "Does the contract contain any provisions related to PAC? What is formal PAC? Any provision which points to deemed PAC?.Do not include introductory statements highlight the key points.",
#     "Summarise FAC any FAC requirements included in the document, including procedure for return of project securities and retention bond if any.Do not include introductory statements highlight the key points.",
#     "What are provisions that go beyond ABB HSE requirements? Consequence of not complying?.Do not include introductory statements highlight the key points.",
#     "Is the integrity provision in line with ABB's integrity policy? Do the integrity provisions go beyond ABB requirements? Does What are the consequence of not complying to the integrity provisions covered in the contract?.Do not include introductory statements highlight the key points.",
#     "What is the order of preceedence/ Prioritry of Documents/ Hierarchy of the contract documents.Do not include introductory statements highlight the key points.",
#     "What are the applicable dispute resolution provisions/ mechanisms under the contract? What are the steps for dispute resolution stated in the contract.Do not include introductory statements highlight the key points.",
#     "Identify the Permits / Imports / Customs that the contractor is responsible for.Do not include introductory statements highlight the key points. ",
#     "Does the contract inlcude provisions for acceleration? Can the employer direct to accelerate even if the contractor is not responsible for the delay?.Do not include introductory statements highlight the key points.",
#     "identify any Incoterm included in the document.Do not include introductory statements highlight the key points.",
#     "Describe whether ABB is entitled to withhold own obligations in case customer does not pay/breaches duty to cooperate/does not provide deliverables etc.Do not include introductory statements highlight the key points.",
#     "Summarise in bullet points the notice requirements and what are preclusive deadlines, and whether there is a timebar effect if the party fails to meet the timelines.Do not include introductory statements highlight the key points.",
#     "Identify the contractual, delivery and input milestones under the contract.Do not include introductory statements highlight the key points."    
# ]

# analytics_ques_list_actual = [
#     "What are the warranty conditions mentioned in the document. Also include duration of the warranty (in months/years), any conditions or limitations, notices, and any specific provisions related to the warranty coverage for the products or services.Do not include introductory statements highlight the key points.Please include the page number(s) where this is mentioned.",
#     "Extract the details of the governing law explicitly mentioned in the document, including the country or jurisdiction. If referenced in other clauses, annexures, or paragraphs, include those cross-references with exact page numbers and clause/section/paragraph IDs. Present the information concisely, highlighting only key points. If the governing law details span multiple sections, consolidate all relevant information.Do not include introductory statements highlight the key points.",
#     "Summarize tax provisions in the document, including any relevant details on tax obligations, exemptions, and procedures related to taxation for the parties involved.Do not include introductory statements highlight the key points.",
#     "Summarize the requirements, deadlines, and procedures for any performance security (e.g., letter of credit, parent company guarantee, bond, or other guarantees) that ABB must provide under the contract. Include specific details with exact page numbers and clause/section/paragraph IDs. If references span multiple sections, consolidate the information.Do not include introductory statements highlight the key points.",
#     "Does the contract include provisions for termination by the contractor? If yes, summarize the provisions for termination (e.g., employer's default, convenience, or other reasons) as outlined in the document. Include conditions, reasons, and procedures specified for the contractor's right to terminate, along with exact page numbers and clause/section/paragraph IDs.If the provisions refer to other clauses, sections, or paragraphs elsewhere in the document (e.g., annexures or cross-references), explicitly mention these references in the response.Consolidate details from multiple sections into a cohesive summary.Do not include introductory statements highlight the key points.",
#     "Are there any prerequisites in the document for the commencement of work, such as the requirement of a Notice to Proceed or the issuance of a Purchase Order? Summarize:*Specific prerequisites or conditions that must be fulfilled before work commencement, including details of any Notice to Proceed or Purchase Order requirements.* Timeframes or deadlines for fulfilling these prerequisites. Provide exact page numbers and clause/section/paragraph IDs in your response. If the prerequisites or related procedures reference other clauses, sections, or paragraphs (e.g., annexures or cross-references), explicitly mention these references and consolidate the details into a clear and comprehensive summary.Do not include introductory statements highlight the key points.",
#     "Summarize the limitation on liability mentioned in the document in 2 or 3 sentence. Does the document have a limitation of liability provision? Specify the limit and any exclusions, if any.Do not include introductory statements highlight the key points.",
#     "Summarize liability for liquidated damages provisions, including delay liquidated damages and performance liquidated damages, applicable cap and whether they are exclusive remedies.Do not include introductory statements highlight the key points.",
#     "Summarize price adjustment or escalation modality outlined in the document, including any terms, conditions, and mechanisms related to adjustments or escalations in pricing over time.Do not include introductory statements highlight the key points.",
#     "Give the details about the extension of time as mentioned in the document and summarise procedure to claim extension of time.Do not include introductory statements highlight the key points.",
#     "Are there any service level agreement (SLA) in the document?.Do not include introductory statements highlight the key points.",
#     "Give a summary of insurance terms in bullet points along with procedures to claim it.Do not include introductory statements highlight the key points.",
#     "Summarize confidentiality obligations outlined in the  document, including any relevant terms, conditions, and obligations pertaining to the protection of sensitive information.Do not include introductory statements highlight the key points.",
#     "What are the country specific requirements for permanent establishment? What are the requirements for permanent assets in the country?.Do not include introductory statements highlight the key points.",
#     "Are there conditions in the document allowing the employer to withhold a proportion of payment as retention from the contractor? Summarize:*The specific conditions under which retention money can be withheld from payments due to the contractor.*The procedures and conditions for the release of the retention money, including timelines or milestones specifying when the retention money, or part thereof, must be paid back to the contractor. Provide exact page numbers and clause/section/paragraph IDs in your response. If the retention-related conditions or procedures reference other clauses, sections, or paragraphs (e.g., annexures or cross-references), explicitly mention these references and consolidate the details into a clear and comprehensive summary.Do not include introductory statements highlight the key points.",
#     "Extract and summarize the payment terms specified in the document, including details on payment methods, deadlines, and any conditions or requirements related to the payment transactions between the parties.Precisely provide the exact prompt response highlighting the key points.Do not include introductory statements highlight the key points.",
#     "Are consequential losses excluded or limited. Does the document have an exclusion for consequential losses provision? Specify any exclusions, if any.Do not include introductory statements highlight the key points.",
#     "Are there any indemnity provisions in the contract? What is the extent of indemnification and who is to be indemnified? Are indemnities included/capped under the limitaton of liability provision?.Do not include introductory statements highlight the key points.",
#     "Does the contract have a change in law provision? Please specify any exclusions, if any.Do not include introductory statements highlight the key points.",
#     "Does the contract include the right to terminate for force majeure/exceptional events? If yes, who has the right to terminate and under what circumstances. What is the notification period for such events and is there any specific format stipulated by the contract in which such event is to be notified?  Identify provisions that differs from ABB requirements/standards (e.g. Material shortage, ripple effect, COVID-19).Do not include introductory statements highlight the key points.",
#     "Summarise in bullet point format the causes for suspension by contractor or employer? What is the notification period for such suspension events and is there any specific format stipulated by the contract in which such event is to be notified? Can the contractor claim costs due to a suspension? if yes, under what circumstances.  Does the document include right to terminate for suspension? If yes, who has the right to terminate and under what circumstances.Do not include introductory statements highlight the key points.",
#     "Does the contract contain provisions for termination by the employer? Summarize the circumstances entitling the employer to terminate, including:*Provisions for termination for convenience, listing the contractor's recoverable costs, expenses, and any other relevant details.*Provisions for termination due to breach of contract by the contractor, including any period or deadline by which the contractor must respond or take corrective action to avoid termination.Include exact page numbers and clause/section/paragraph IDs in your response. If the provisions reference other clauses, sections, or paragraphs elsewhere in the document (e.g., annexures or cross-references), explicitly mention these references and consolidate the details into a cohesive summary.Do not include introductory statements highlight the key points",
#     "Does the contract allow the employer to direct/instruct  the contractor to perform a variation/change before mutual agreement? What are the conditions in which a variation or change order is claimable? What are the notification requirements? What is the timebar requirement? Is there a procedure to invoice changes/ variations? Does the contractor have a duty to perform and upon which conditions? Can the contractor reject a variation/change if it does not align with geographical and scope connectivity?.Do not include introductory statements highlight the key points.",
#     "Does the contract contain any provisions related to PAC? What is formal PAC? Any provision which points to deemed PAC?.Do not include introductory statements highlight the key points.",
#     "Summarise FAC any FAC requirements included in the document, including procedure for return of project securities and retention bond if any.Do not include introductory statements highlight the key points.",
#     "What are provisions that go beyond ABB HSE requirements? Consequence of not complying?.Do not include introductory statements highlight the key points.",
#     "Is the integrity provision in line with ABB's integrity policy? Do the integrity provisions go beyond ABB requirements? Does What are the consequence of not complying to the integrity provisions covered in the contract?.Do not include introductory statements highlight the key points.",
#     "Locate and list the precedence rules or priorities described in the document, including exact terminology such as Order of Precedence, Priority of Documents, or Hierarchy of Contract Documents.If any precedence rules reference other sections or clauses (e.g., paragraph 1.2(a)), extract the full content of the referenced section, clause, or annexure, and include it explicitly in the response.Ensure that the final response clearly resolves all references, providing the hierarchy of documents in its entirety.Include precise page numbers and clause or section IDs where the precedence rules and referenced content are found.",
#     "What are the applicable dispute resolution provisions/ mechanisms under the contract? What are the steps for dispute resolution stated in the contract.Do not include introductory statements highlight the key points.",
#     "Identify the Permits / Imports / Customs that the contractor is responsible for.Do not include introductory statements highlight the key points. ",
#     "Does the contract inlcude provisions for acceleration? Can the employer direct to accelerate even if the contractor is not responsible for the delay?.Do not include introductory statements highlight the key points.",
#     "identify any Incoterm included in the document.Do not include introductory statements highlight the key points.",
#     "Describe whether ABB is entitled to withhold own obligations in case customer does not pay/breaches duty to cooperate/does not provide deliverables etc.Do not include introductory statements highlight the key points.",
#     "Summarise in bullet points the notice requirements and what are preclusive deadlines, and whether there is a timebar effect if the party fails to meet the timelines.Do not include introductory statements highlight the key points.",
#     "Identify the contractual, delivery and input milestones under the contract.Do not include introductory statements highlight the key points."    
# ]

analytics_ques_list = [
    "What are the warranty conditions mentioned in the document. Also include duration of the warranty (in months/years), any conditions or limitations, notices, and any specific provisions related to the warranty coverage for the products or services.Do not include introductory statements highlight the key points.Please include the page number(s) where this is mentioned.",
    "Give the details of the governing law as mentioned in the document.Extract the details of the governing law explicitly mentioned in the document, including the country or jurisdiction. If referenced in other clauses, annexures, or paragraphs, include those cross-references with exact page numbers and clause/section/paragraph IDs. Present the information concisely, highlighting only key points. If the governing law details span multiple sections, consolidate all relevant information.Do not include introductory statements highlight the key points.",
    "Summarize tax provisions in the document, including any relevant details on tax obligations, exemptions, and procedures related to taxation for the parties involved.Do not include introductory statements highlight the key points.",
    "Summarize the details of the requirements along with period/deadlines and procedures for any security for performance in the form of a letter of credit, parent company guarantee, bond and or guarantee that ABB must provide under the contract.Include specific details with exact page numbers.If references span multiple sections, consolidate the information.Do not include introductory statements highlight the key points.",
    "Does the contract contain provisions for termination by Contractor? If yes, summarize the provisions related to termination by contractor (for employer’s default, for convenience, or other) as speci-fied in the document, including any conditions, reasons, and proce-dures outlined for the contractor's right to terminate the contract.Do not include introductory statements highlight the key points.",
    "Are there any pre-requisites for the commencement of work men-tioned in the document, including any requirements of a Notice to Proceed or the issuance of a Purchase Order.If yes, provide details, including timeframes/deadlines, for fulfilling said pre-requisites.If the prerequisites or related procedures reference other clauses, sections, or paragraphs explicitly mention these references and consolidate the details into a clear and comprehensive summary.Do not include introductory statements highlight the key points.",
    "Summarize the limitation on liability mentioned in the document in 2 or 3 sentence. Does the document have a limitation of liability provision? Specify the limit and any exclusions, if any.Do not include introductory statements highlight the key points.",
    "Summarize liability for liquidated damages provisions, including delay liquidated damages and performance liquidated damages, applicable cap and whether they are exclusive remedies.Do not include introductory statements highlight the key points.",
    "Summarize price adjustment or escalation modality outlined in the document, including any terms, conditions, and mechanisms related to adjustments or escalations in pricing over time.Do not include introductory statements highlight the key points.",
    "Give the details about the extension of time as mentioned in the document and summarise procedure to claim extension of time.Do not include introductory statements highlight the key points.",
    "Are there any service level agreement (SLA) in the document?.Do not include introductory statements highlight the key points.",
    "Give a summary of insurance terms in bullet points along with procedures to claim it.Do not include introductory statements highlight the key points.",
    "Summarize confidentiality obligations outlined in the  document, including any relevant terms, conditions, and obligations pertaining to the protection of sensitive information.Do not include introductory statements highlight the key points.",
    "What are the country specific requirements for permanent establishment? What are the requirements for permanent assets in the country?.Do not include introductory statements highlight the key points.",
    "Are there any conditions mentioned in the document allowing the employer to withhold, as retention, a proportion of an amount of money due to the contractor from a payment? Additionally, summa-rise the conditions and procedures for the release of the retention including the point at which the retention money, or part thereof, is required to be paid back to the contractor?.If the retention-related conditions or procedures reference other clauses, sections, or paragraphs, explicitly mention these references and consolidate the details into a clear and comprehensive summary.Do not include introductory statements highlight the key points.",
    "Extract and summarize the payment terms specified in the document, including details on payment methods, deadlines, and any conditions or requirements related to the payment transactions between the parties.Precisely provide the exact prompt response highlighting the key points.Do not include introductory statements highlight the key points.",
    "Are consequential losses excluded or limited. Does the document have an exclusion for consequential losses provision? Specify any exclusions, if any.Do not include introductory statements highlight the key points.",
    "Are there any indemnity provisions in the contract? What is the extent of indemnification and who is to be indemnified? Are indemnities included/capped under the limitaton of liability provision?.Do not include introductory statements highlight the key points.",
    "Does the contract have a change in law provision? Please specify any exclusions, if any.Do not include introductory statements highlight the key points.",
    "Does the contract include the right to terminate for force majeure/exceptional events? If yes, who has the right to terminate and under what circumstances. What is the notification period for such events and is there any specific format stipulated by the contract in which such event is to be notified?  Identify provisions that differs from ABB requirements/standards (e.g. Material shortage, ripple effect, COVID-19).Do not include introductory statements highlight the key points.",
    "Summarise in bullet point format the causes for suspension by contractor or employer? What is the notification period for such suspension events and is there any specific format stipulated by the contract in which such event is to be notified? Can the contractor claim costs due to a suspension? if yes, under what circumstances.  Does the document include right to terminate for suspension? If yes, who has the right to terminate and under what circumstances.Do not include introductory statements highlight the key points.",
    "Does the contract contain provisions for termination by employer?  When does it entitle the employer to terminate? Summarise any provisions entitling the employer to terminate for convenience, in-cluding list contractor’s recoverable costs and expenses and other relevant information? What are the termination provisions due to breach of contract by contractor? Is there a period/deadline by which the contractor is required to respond or take action to avoid termination by the employer due to contractor’s breach?.If the provisions reference other clauses, sections, or paragraphs elsewhere in the document (e.g., annexures or cross-references), explicitly mention these references and consolidate the details into a cohesive summary.Do not include introductory statements highlight the key points",
    "Does the contract allow the employer to direct/instruct  the contractor to perform a variation/change before mutual agreement? What are the conditions in which a variation or change order is claimable? What are the notification requirements? What is the timebar requirement? Is there a procedure to invoice changes/ variations? Does the contractor have a duty to perform and upon which conditions? Can the contractor reject a variation/change if it does not align with geographical and scope connectivity?.Do not include introductory statements highlight the key points.",
    "Does the contract contain any provisions related to PAC? What is formal PAC? Any provision which points to deemed PAC?.Do not include introductory statements highlight the key points.",
    "Summarise FAC any FAC requirements included in the document, including procedure for return of project securities and retention bond if any.Do not include introductory statements highlight the key points.",
    "What are provisions that go beyond ABB HSE requirements? Consequence of not complying?.Do not include introductory statements highlight the key points.",
    "Is the integrity provision in line with ABB's integrity policy? Do the integrity provisions go beyond ABB requirements? Does What are the consequence of not complying to the integrity provisions covered in the contract?.Do not include introductory statements highlight the key points.",
    "Locate and list the precedence rules or priorities described in the document, including exact terminology such as Order of Precedence, Priority of Documents, or Hierarchy of Contract Documents.If any precedence rules reference other sections or clauses (e.g., paragraph 1.2(a)), extract the full content of the referenced section, clause, or annexure, and include it explicitly in the response.Ensure that the final response clearly resolves all references, providing the hierarchy of documents in its entirety.Include precise page numbers and clause or section IDs where the precedence rules and referenced content are found.",
    "What are the applicable dispute resolution provisions/ mechanisms under the contract? What are the steps for dispute resolution stated in the contract.Do not include introductory statements highlight the key points.",
    "Identify the Permits / Imports / Customs that the contractor is responsible for.Do not include introductory statements highlight the key points. ",
    "Does the contract inlcude provisions for acceleration? Can the employer direct to accelerate even if the contractor is not responsible for the delay?.Do not include introductory statements highlight the key points.",
    "identify any Incoterm included in the document.Do not include introductory statements highlight the key points.",
    "Describe whether ABB is entitled to withhold own obligations in case customer does not pay/breaches duty to cooperate/does not provide deliverables etc.Do not include introductory statements highlight the key points.",
    "Summarise in bullet points the notice requirements and what are preclusive deadlines, and whether there is a timebar effect if the party fails to meet the timelines.Do not include introductory statements highlight the key points.",
    "Identify the contractual, delivery and input milestones under the contract.Do not include introductory statements highlight the key points."    
]